/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Codigo;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;



/**
 *
 * @author Lab A
 */
public class frmInicio extends javax.swing.JFrame {
    
    ImageIcon Cromo=new ImageIcon();
    ImageIcon Escala=new ImageIcon();
    AutoByteDB you = new AutoByteDB();
    Connection cn = you.conexion();
    
    static String user,usuario,pass,contra;
    int i,sh=1;

     frmInicio() {
        initComponents();
        
     Cromo=new ImageIcon(getClass().getResource("/Imagenes/lblinicio.png"));
     Escala=new ImageIcon(Cromo.getImage().getScaledInstance(lblFondo.getWidth(),lblFondo.getHeight(),Image.SCALE_DEFAULT));
     lblFondo.setIcon(Escala);
     
     Cromo=new ImageIcon(getClass().getResource("/Imagenes/lblLogin.jpg"));
     Escala=new ImageIcon(Cromo.getImage().getScaledInstance(lblLogin.getWidth(),lblLogin.getHeight(),Image.SCALE_DEFAULT));
     lblLogin.setIcon(Escala);
     Cromo=new ImageIcon(getClass().getResource("/Imagenes/lblLogin.jpg"));
     Escala=new ImageIcon(Cromo.getImage().getScaledInstance(lblRegister.getWidth(),lblRegister.getHeight(),Image.SCALE_DEFAULT));
     lblRegister.setIcon(Escala);
     
     setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icon.png")).getImage());
     
     panRegister.setVisible(false);
     lblRegister.setVisible(false);
     
     txtContra.setVisible(false);
     btnHide.setVisible(false);
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        panRegister = new javax.swing.JPanel();
        txtNUsuario = new javax.swing.JTextField();
        txtpNContra = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        btnHaveAcc = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        txtNCorreo = new javax.swing.JTextField();
        txtNNombre = new javax.swing.JTextField();
        txtNApellidos = new javax.swing.JTextField();
        txtNNumero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panLogin = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        txtContra = new javax.swing.JTextField();
        txtpContra = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btnNoAcc = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnHide = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        lblLogin = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panRegister.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N
        panRegister.setOpaque(false);

        txtNUsuario.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtNUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NUEVO USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        txtpNContra.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtpNContra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpNContra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NUEVA CONTRASEÑA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("¿Ya tienes cuenta?");

        btnHaveAcc.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 10)); // NOI18N
        btnHaveAcc.setForeground(new java.awt.Color(0, 0, 100));
        btnHaveAcc.setText("Click Aquí");
        btnHaveAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHaveAccActionPerformed(evt);
            }
        });

        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnregister.png"))); // NOI18N
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        txtNCorreo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtNCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNCorreo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CORREO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        txtNNombre.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtNNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOMBRE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N
        txtNNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNNombreActionPerformed(evt);
            }
        });

        txtNApellidos.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtNApellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNApellidos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "APELLIDOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        txtNNumero.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtNNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNNumero.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NUMERO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DIRECCION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout panRegisterLayout = new javax.swing.GroupLayout(panRegister);
        panRegister.setLayout(panRegisterLayout);
        panRegisterLayout.setHorizontalGroup(
            panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRegisterLayout.createSequentialGroup()
                .addGroup(panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panRegisterLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtNUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtpNContra, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panRegisterLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panRegisterLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(btnHaveAcc))
                    .addGroup(panRegisterLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panRegisterLayout.createSequentialGroup()
                                .addComponent(txtNNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(panRegisterLayout.createSequentialGroup()
                                .addComponent(txtNCorreo)
                                .addGap(18, 18, 18)))
                        .addGroup(panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(txtNNumero))))
                .addGap(10, 10, 10))
        );
        panRegisterLayout.setVerticalGroup(
            panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRegisterLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(txtpNContra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(txtNNumero))
                .addGap(7, 7, 7)
                .addGroup(panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panRegisterLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panRegisterLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2))
                    .addComponent(btnHaveAcc)))
        );

        getContentPane().add(panRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 80, 530, 440));

        panLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INICIAR SESION", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N
        panLogin.setOpaque(false);
        panLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N
        panLogin.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 70, 240, 63));

        txtContra.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtContra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTRASEÑA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N
        panLogin.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 163, 240, 63));

        txtpContra.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtpContra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpContra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTRASEÑA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N
        panLogin.add(txtpContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 163, 240, 63));

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("¿No tienes cuenta?");
        panLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 400, -1, -1));

        btnNoAcc.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 10)); // NOI18N
        btnNoAcc.setForeground(new java.awt.Color(0, 0, 100));
        btnNoAcc.setText("Click Aquí");
        btnNoAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoAccActionPerformed(evt);
            }
        });
        panLogin.add(btnNoAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 399, -1, -1));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnlogin.png"))); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 276, 80, 80));

        btnHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnhide.png"))); // NOI18N
        btnHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHideActionPerformed(evt);
            }
        });
        panLogin.add(btnHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 183, 30, 30));

        btnShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnshow.png"))); // NOI18N
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        panLogin.add(btnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 183, 30, 30));

        getContentPane().add(panLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 340, 430));
        getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 340, 430));
        getContentPane().add(lblRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 80, 530, 470));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNoAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoAccActionPerformed
       
        panRegister.setVisible(true);
        lblRegister.setVisible(true);
        panLogin.setVisible(false);
        lblLogin.setVisible(false);
    }//GEN-LAST:event_btnNoAccActionPerformed

    private void btnHaveAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHaveAccActionPerformed
        
        panRegister.setVisible(false);
        lblRegister.setVisible(false);
        panLogin.setVisible(true);
        lblLogin.setVisible(true);

    }//GEN-LAST:event_btnHaveAccActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            user=txtUsuario.getText();
            if(sh==0){
                pass=txtContra.getText();
            }
            else {
                pass=txtpContra.getText();
            }
            String query="SELECT * FROM cuentas WHERE user='"+user+"' and pass='"+pass+"'";
            Statement st = cn.createStatement();
            ResultSet rs=st.executeQuery(query);
            if (rs.next()){
                dispose();
                new frmVentas().setVisible(true);
            }
            else {
                dispose();
            for(i=1;i<=3;i++) 
            {
                JOptionPane.showMessageDialog(null, "Inicio de sesión fallido, intente de nuevo");
                user=JOptionPane.showInputDialog("Intento: "+i+"/3\n\nIngresa Usuario:");
                pass=JOptionPane.showInputDialog("Intento: "+i+"/3\n\nIngresa Contraseña:");
                
                query="SELECT * FROM cuentas WHERE user='"+user+"' and pass='"+pass+"'";
                st = cn.createStatement();
                rs=st.executeQuery(query);
                
                
                if(rs.next()) 
                {
                    dispose();
                    new frmVentas().setVisible(true);
                    i=5;
                }
                else if(i==3)
                {
                    JOptionPane.showMessageDialog(null, "NO HAY INTENTOS DISPONIBLES!!\nCERRANDO PROGRAMA...");
                    System.exit(0);
                }
            }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERROR");
            
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
           try
        {
            PreparedStatement pst = cn.prepareStatement("INSERT INTO cuentas(user,pass,nombre,apellidos,numero,email,direccion"
                + ") VALUES(?,?,?,?,?,?,?)");
            pst.setString(1,txtNUsuario.getText());
            pst.setString(2,txtpNContra.getText());
            pst.setString(3,txtNNombre.getText());
            pst.setString(4,txtNApellidos.getText());
            pst.setString(5,String.valueOf(txtNNumero.getText()));
            pst.setString(6,txtNCorreo.getText());
            pst.setString(7,jTextArea1.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Se ha creado el registro exitosamente");
            panRegister.setVisible(false);
            panLogin.setVisible(true);
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "El usuario no se puede registrar");
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtNNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNNombreActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        sh=0;
        txtContra.setText(txtpContra.getText());
        txtpContra.setVisible(false);
        txtContra.setVisible(true);
        btnShow.setVisible(false);
        btnHide.setVisible(true);
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHideActionPerformed
        sh=1;
        txtpContra.setText(txtContra.getText());
        txtpContra.setVisible(true);
        txtContra.setVisible(false);
        btnShow.setVisible(true);
        btnHide.setVisible(false);
    }//GEN-LAST:event_btnHideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHaveAcc;
    private javax.swing.JButton btnHide;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnNoAcc;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnShow;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JPanel panLogin;
    private javax.swing.JPanel panRegister;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtNApellidos;
    private javax.swing.JTextField txtNCorreo;
    private javax.swing.JTextField txtNNombre;
    private javax.swing.JTextField txtNNumero;
    private javax.swing.JTextField txtNUsuario;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JPasswordField txtpContra;
    private javax.swing.JPasswordField txtpNContra;
    // End of variables declaration//GEN-END:variables
}
