/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Codigo;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;


import java.io.InputStream; //ver cboModelos
/**
 *
 * @author Lab A
 */
public class frmMarcas extends javax.swing.JFrame {
    ImageIcon Cromo=new ImageIcon();
    ImageIcon Escala=new ImageIcon();
    AutoByteDB you = new AutoByteDB();
    Connection cn = you.conexion();
    static String marca,smodelo="MODELOS",modelo,adicionales="";
    String logomarca,sqlmodelos,imgmodelo;
    static double subtotadicionales=0.0,subtotauto;
    int confirm;
    
    
    /**
     * Creates new form frmMarcas
     */
    public frmMarcas() {
        initComponents();
        Cromo=new ImageIcon(getClass().getResource("/Imagenes/frmMarcas.jpg"));
        Escala=new ImageIcon(Cromo.getImage().getScaledInstance(lblFondo.getWidth(),lblFondo.getHeight(),Image.SCALE_DEFAULT));
        lblFondo.setIcon(Escala);
        
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icon.png")).getImage());
        
        marca="SELECCIONE";
        while (frmMarcas.marca.equals("SELECCIONE")){
        marca=(String.valueOf(JOptionPane.showInputDialog(null,
         "ELIJA UNA MARCA","SELECCIONE",
      JOptionPane.QUESTION_MESSAGE,null,new Object[]{"SELECCIONE","KIA","CHEVROLET",
          "FORD","NISSAN","TOYOTA"},"SELECCIONE")));
        }
            Cromo=new ImageIcon(getClass().getResource("/Imagenes/modelos.jpg"));
            Escala=new ImageIcon(Cromo.getImage().getScaledInstance(lblModelo.getWidth(),lblModelo.getHeight(),Image.SCALE_DEFAULT));
            lblModelo.setIcon(Escala);
        
        switch(marca) {
                case "KIA": logomarca="Kia.png";
                break;
                case "CHEVROLET": logomarca="chevrolet.jpg";
                break;
                case "NISSAN": logomarca="nissan.jpg";
                break;
                case "FORD": logomarca="ford.jpg";
                break;
                case "TOYOTA": logomarca="toyota.png";
                break;
                default: 
                    dispose();
                    new frmVentas().setVisible(true);                    
                break;
             
                
        }
        Cromo=new ImageIcon(getClass().getResource("/Imagenes/"+logomarca));
        Escala=new ImageIcon(Cromo.getImage().getScaledInstance(lblLogo.getWidth(),lblLogo.getHeight(),Image.SCALE_DEFAULT));
        lblLogo.setIcon(Escala);
        
        txtComprador.setText(frmVentas.nombre);
        txtNumero.setText(frmVentas.numero);
        lblMarca.setText(marca);
        
        sqlmodelos = "SELECT nombre FROM almacen WHERE marca = '"+marca+"'";
        
        try {
        Statement stm = cn.createStatement();
        ResultSet rsm = stm.executeQuery(sqlmodelos);
        while(rsm.next()){
            
            cboModelos.addItem(rsm.getString(1));
            
        }
        
        }
        catch(SQLException ex)
                {
                    JOptionPane.showMessageDialog(null, ex);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbllogo = new javax.swing.JLabel();
        lblLema = new javax.swing.JLabel();
        panComprador = new javax.swing.JPanel();
        txtComprador = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cboModelos = new javax.swing.JComboBox<>();
        lblModelo = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        panAdicionales = new javax.swing.JPanel();
        chkEsponja = new javax.swing.JCheckBox();
        chkAromatizantes = new javax.swing.JCheckBox();
        chkFundas = new javax.swing.JCheckBox();
        chkToalla = new javax.swing.JCheckBox();
        chkCalcomania = new javax.swing.JCheckBox();
        lblMarca = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo mini.jpg"))); // NOI18N
        lbllogo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 100, -1));

        lblLema.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 18)); // NOI18N
        lblLema.setForeground(new java.awt.Color(255, 0, 51));
        lblLema.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLema.setText("\"Comprometidos con la seguridad,  dedicados a tu satisfaccion\"");
        lblLema.setToolTipText("");
        lblLema.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblLema, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 550, 30));

        panComprador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Comprador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(255, 0, 51))); // NOI18N
        panComprador.setOpaque(false);

        txtComprador.setEditable(false);
        txtComprador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtComprador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        txtNumero.setEditable(false);
        txtNumero.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Numero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        javax.swing.GroupLayout panCompradorLayout = new javax.swing.GroupLayout(panComprador);
        panComprador.setLayout(panCompradorLayout);
        panCompradorLayout.setHorizontalGroup(
            panCompradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCompradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panCompradorLayout.setVerticalGroup(
            panCompradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCompradorLayout.createSequentialGroup()
                .addGroup(panCompradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        getContentPane().add(panComprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 100));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setEnabled(false);
        jPanel1.setOpaque(false);

        cboModelos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cboModelos.setForeground(new java.awt.Color(0, 102, 255));
        cboModelos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MODELOS" }));
        cboModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboModelosActionPerformed(evt);
            }
        });

        lblModelo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cboModelos, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboModelos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 320, 250));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnvolver.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 60, 60));

        btnComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btncomprar.png"))); // NOI18N
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 80, 80));

        panAdicionales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADICIONALES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14), new java.awt.Color(51, 51, 255))); // NOI18N
        panAdicionales.setOpaque(false);

        chkEsponja.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        chkEsponja.setForeground(new java.awt.Color(0, 102, 255));
        chkEsponja.setText("ESPONJA $119.99");
        chkEsponja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/esponja.png"))); // NOI18N
        chkEsponja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsponjaActionPerformed(evt);
            }
        });

        chkAromatizantes.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        chkAromatizantes.setForeground(new java.awt.Color(51, 102, 255));
        chkAromatizantes.setText("AROMATIZANTE $89.99");
        chkAromatizantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aromi.png"))); // NOI18N
        chkAromatizantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAromatizantesActionPerformed(evt);
            }
        });

        chkFundas.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        chkFundas.setForeground(new java.awt.Color(0, 102, 204));
        chkFundas.setText("FUNDAS DE VOLANTE $169.99");
        chkFundas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/funda.png"))); // NOI18N
        chkFundas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFundasActionPerformed(evt);
            }
        });

        chkToalla.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        chkToalla.setForeground(new java.awt.Color(0, 102, 204));
        chkToalla.setText("TOALLA DE LAVADO $499.99");
        chkToalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/toalla.jpg"))); // NOI18N
        chkToalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkToallaActionPerformed(evt);
            }
        });

        chkCalcomania.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        chkCalcomania.setForeground(new java.awt.Color(0, 102, 204));
        chkCalcomania.setText("CALCOMANIAS $79.99");
        chkCalcomania.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calco.jpg"))); // NOI18N
        chkCalcomania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCalcomaniaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panAdicionalesLayout = new javax.swing.GroupLayout(panAdicionales);
        panAdicionales.setLayout(panAdicionalesLayout);
        panAdicionalesLayout.setHorizontalGroup(
            panAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAdicionalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkEsponja)
                    .addComponent(chkAromatizantes)
                    .addComponent(chkFundas)
                    .addComponent(chkToalla)
                    .addComponent(chkCalcomania))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panAdicionalesLayout.setVerticalGroup(
            panAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAdicionalesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(chkEsponja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkAromatizantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkFundas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkToalla)
                .addGap(18, 18, 18)
                .addComponent(chkCalcomania)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(panAdicionales, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 310, 400));

        lblMarca.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(255, 255, 255));
        lblMarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMarca.setText("NOMBRE DE LA MARCA");
        getContentPane().add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 280, 30));

        lblLogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 157, 134));

        lblFondo.setOpaque(true);
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
   
    
    private void cboModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboModelosActionPerformed
        /* Nescesitaba validar si la imagen existe o no, esto para evitar errores
        si alguien da de alta en la base de datos un modelo del cual no hayan imagenes
        
        Intente con la clase .isFile() y .exists() pero si usaba la misma ruta que se usa para el 
        ImageIcon me mandaba a C:\Imagenes\  lugar de a la ruta de Imagenes de el proyecto
        
        Usé  getResourceAsStream() para obtener un flujo de entrada (InputStream) 
        y luego cargar la imagen desde el flujo de entrada ya que con getResource() no funcionaba,
        además deberia funcionar aun con el proyecto ya compilado
        
        https://www.geeksforgeeks.org/class-getresourceasstream-method-in-java-with-examples/
        
        */
        smodelo = cboModelos.getSelectedItem().toString().toLowerCase();
        InputStream inputStream = getClass().getResourceAsStream("/Imagenes/" + smodelo + ".jpg");

        if (inputStream != null) {
        // La imagen existe 
        imgmodelo = smodelo;
        }
        else {
        // La imagen no existe
        imgmodelo = "modelos";
        }      
        
        
        Cromo=new ImageIcon(getClass().getResource("/Imagenes/"+imgmodelo+".jpg"));
        Escala=new ImageIcon(Cromo.getImage().getScaledInstance(lblModelo.getWidth(),lblModelo.getHeight(),Image.SCALE_DEFAULT));
        lblModelo.setIcon(Escala); 
    }//GEN-LAST:event_cboModelosActionPerformed

    private void chkAromatizantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAromatizantesActionPerformed
        if(chkAromatizantes.isSelected())
        chkAromatizantes.setText(chkAromatizantes.getText()+"*");
        else
        chkAromatizantes.setText(chkAromatizantes.getText().replace("*", ""));
    }//GEN-LAST:event_chkAromatizantesActionPerformed

    private void chkToallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkToallaActionPerformed
        if(chkToalla.isSelected())
        chkToalla.setText(chkToalla.getText()+"*");
        else
        chkToalla.setText(chkToalla.getText().replace("*", ""));
    }//GEN-LAST:event_chkToallaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        dispose();
        new frmVentas().setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        frmVentas.autocompra="";
        modelo=smodelo;
        if (chkEsponja.isSelected()) {
            subtotadicionales += 119.99;
            adicionales+="Esponja\n";
        }

        if (chkAromatizantes.isSelected()) {
            subtotadicionales += 89.99;
            adicionales+="Aromatizante\n";
        }

        if (chkFundas.isSelected()) {
            subtotadicionales += 169.99;
            adicionales+="Funda\n";
        }

        if (chkToalla.isSelected()) {
            subtotadicionales += 489.99;
            adicionales+="Toalla\n";
        }   

        if (chkCalcomania.isSelected()) {
            subtotadicionales += 79.99;
            adicionales+="Calcomania\n";
        }
        
        if (smodelo.equals("MODELOS")){
            JOptionPane.showMessageDialog(null, "Seleccione un auto primero");
        }
        else{
            String query = "SELECT costo FROM almacen WHERE nombre = '"+smodelo+"'";
            try {
                Statement stm = cn.createStatement();
                ResultSet rsm = stm.executeQuery(query);
                if (rsm.next()) {
                    
                    subtotauto=Double.parseDouble(rsm.getString(1));
                    confirm=JOptionPane.showConfirmDialog(null, "¿Desea comprar refacciones?", "CONFIRMAR",
				JOptionPane.YES_NO_OPTION);
                    
                    if (confirm==0) {
                        frmPartes.volver=1;
                        dispose();
                        new frmPartes().setVisible(true);
                        }
                    else {
                       frmTicket.volver=1;
                        dispose();
                        new frmTicket().setVisible(true); 
                    }
                    }
                else {
                    JOptionPane.showMessageDialog(null, "Este auto no está disponible por el momento:(");
                    }
            }
            catch(SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
            }
        }
        
        
    }//GEN-LAST:event_btnComprarActionPerformed

    private void chkEsponjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsponjaActionPerformed
        if(chkEsponja.isSelected())
        chkEsponja.setText(chkEsponja.getText()+"*");
        else
        chkEsponja.setText(chkEsponja.getText().replace("*", ""));
    }//GEN-LAST:event_chkEsponjaActionPerformed

    private void chkFundasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFundasActionPerformed
        if(chkFundas.isSelected())
        chkFundas.setText(chkFundas.getText()+"*");
        else
        chkFundas.setText(chkFundas.getText().replace("*", ""));
    }//GEN-LAST:event_chkFundasActionPerformed

    private void chkCalcomaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCalcomaniaActionPerformed
        if(chkCalcomania.isSelected())
        chkCalcomania.setText(chkCalcomania.getText()+"*");
        else
        chkCalcomania.setText(chkCalcomania.getText().replace("*", ""));
    }//GEN-LAST:event_chkCalcomaniaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMarcas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cboModelos;
    private javax.swing.JCheckBox chkAromatizantes;
    private javax.swing.JCheckBox chkCalcomania;
    private javax.swing.JCheckBox chkEsponja;
    private javax.swing.JCheckBox chkFundas;
    private javax.swing.JCheckBox chkToalla;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLema;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JPanel panAdicionales;
    private javax.swing.JPanel panComprador;
    private javax.swing.JTextField txtComprador;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
