/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Codigo;
import java.awt.Image;
import javax.swing.ImageIcon;
/**
 *
 * @author Lab A
 */
public class frmMarcas extends javax.swing.JFrame {
    ImageIcon Cromo=new ImageIcon();
    ImageIcon Escala=new ImageIcon();
    /**
     * Creates new form frmMarcas
     */
    public frmMarcas() {
        initComponents();
        Cromo=new ImageIcon(getClass().getResource("/Imagenes/frmTodo.jpg"));
     Escala=new ImageIcon(Cromo.getImage().getScaledInstance(lblFondo.getWidth(),lblFondo.getHeight(),Image.SCALE_DEFAULT));
     lblFondo.setIcon(Escala);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbllogo = new javax.swing.JLabel();
        lblLema = new javax.swing.JLabel();
        panComprador = new javax.swing.JPanel();
        txtComprador = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cboModelos = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panAdicionales = new javax.swing.JPanel();
        chkEsponja = new javax.swing.JCheckBox();
        chkAromantizantes = new javax.swing.JCheckBox();
        chkFundas = new javax.swing.JCheckBox();
        chkToalla = new javax.swing.JCheckBox();
        chkCalcomania = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo mini.jpg"))); // NOI18N
        lbllogo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        lblLema.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 18)); // NOI18N
        lblLema.setForeground(new java.awt.Color(255, 0, 51));
        lblLema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLema.setText("\"Comprometidos con la seguridad,  dedicados a tu satisfaccion\"");
        lblLema.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblLema, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 570, 30));

        panComprador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Comprador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(255, 0, 51))); // NOI18N
        panComprador.setOpaque(false);

        txtComprador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtComprador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        txtNumero.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Numero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        javax.swing.GroupLayout panCompradorLayout = new javax.swing.GroupLayout(panComprador);
        panComprador.setLayout(panCompradorLayout);
        panCompradorLayout.setHorizontalGroup(
            panCompradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCompradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panCompradorLayout.setVerticalGroup(
            panCompradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCompradorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panCompradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(panComprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        cboModelos.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cboModelos.setForeground(new java.awt.Color(0, 102, 255));
        cboModelos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MODELOS", "-", "-", "-", "-" }));
        cboModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboModelosActionPerformed(evt);
            }
        });

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("LOGO DE LA MARCA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("FTO DEL MODELO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboModelos, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cboModelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 490, -1));

        panAdicionales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADICIONALES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14), new java.awt.Color(51, 51, 255))); // NOI18N
        panAdicionales.setOpaque(false);

        chkEsponja.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        chkEsponja.setForeground(new java.awt.Color(255, 0, 0));
        chkEsponja.setText("ESPONJA $119.99");
        chkEsponja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/esponja.png"))); // NOI18N

        chkAromantizantes.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        chkAromantizantes.setForeground(new java.awt.Color(255, 0, 0));
        chkAromantizantes.setText("AROMATIZANTE $89.99");
        chkAromantizantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aromi.png"))); // NOI18N
        chkAromantizantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAromantizantesActionPerformed(evt);
            }
        });

        chkFundas.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        chkFundas.setForeground(new java.awt.Color(255, 0, 0));
        chkFundas.setText("FUNDAS DE VOLANTE $169.99");
        chkFundas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/funda.png"))); // NOI18N

        chkToalla.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        chkToalla.setForeground(new java.awt.Color(255, 0, 0));
        chkToalla.setText("TOALLA DE LAVADO $499.99");
        chkToalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/toalla.jpg"))); // NOI18N
        chkToalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkToallaActionPerformed(evt);
            }
        });

        chkCalcomania.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        chkCalcomania.setForeground(new java.awt.Color(255, 0, 0));
        chkCalcomania.setText("CALCOMANIAS $79.99");
        chkCalcomania.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calco.jpg"))); // NOI18N

        javax.swing.GroupLayout panAdicionalesLayout = new javax.swing.GroupLayout(panAdicionales);
        panAdicionales.setLayout(panAdicionalesLayout);
        panAdicionalesLayout.setHorizontalGroup(
            panAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAdicionalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkEsponja)
                    .addComponent(chkAromantizantes)
                    .addComponent(chkFundas)
                    .addComponent(chkToalla)
                    .addComponent(chkCalcomania))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panAdicionalesLayout.setVerticalGroup(
            panAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAdicionalesLayout.createSequentialGroup()
                .addComponent(chkEsponja)
                .addGap(18, 18, 18)
                .addComponent(chkAromantizantes)
                .addGap(18, 18, 18)
                .addComponent(chkFundas)
                .addGap(18, 18, 18)
                .addComponent(chkToalla)
                .addGap(18, 18, 18)
                .addComponent(chkCalcomania)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(panAdicionales, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 280, 420));

        jLabel2.setText("NOMBRE DE LA MARCA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 132, -1));

        lblFondo.setOpaque(true);
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboModelosActionPerformed

        /*switch (cboModelos.getSelectedIndex()) {

            case 0: imgautos="lblAutos.jpg";
            break;
            case 1: imgautos="versa.jpg";
            break;
            case 2: imgautos="NP300.jpg";
            break;
            case 3: imgautos="rio.jpg";
            break;
            case 4: imgautos="aveo.jpg";
            break;
            case 5: imgautos="sentra.jpg";
            break;
            case 6: imgautos="MG5.jpg";
            break;
            case 7: imgautos="March.jpg";
            break;
            case 8: imgautos="Mazda3.jpg";
            break;
            case 9: imgautos="Mazda2.jpg";
            break;
            case 10: imgautos="seltos.jpg";
            break;
            case 11: imgautos="lambo.jpg";
            break;
            case 12: imgautos="camaro.jpg";
            break;
            case 13: imgautos="corvette.jpg";
            break;
            case 14: imgautos="huayra.jpg";
            break;
            case 15: imgautos="koeni.jpg";
            break;
        }

        Cromo=new ImageIcon(getClass().getResource("/Imagenes/"+imgautos));
        Escala=new ImageIcon(Cromo.getImage().getScaledInstance(lblAutos.getWidth(),lblAutos.getHeight(),Image.SCALE_DEFAULT));
        lblAutos.setIcon(Escala);*/
    }//GEN-LAST:event_cboModelosActionPerformed

    private void chkAromantizantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAromantizantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAromantizantesActionPerformed

    private void chkToallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkToallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkToallaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMarcas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboModelos;
    private javax.swing.JCheckBox chkAromantizantes;
    private javax.swing.JCheckBox chkCalcomania;
    private javax.swing.JCheckBox chkEsponja;
    private javax.swing.JCheckBox chkFundas;
    private javax.swing.JCheckBox chkToalla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLema;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JPanel panAdicionales;
    private javax.swing.JPanel panComprador;
    private javax.swing.JTextField txtComprador;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
