/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Codigo;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Lab A
 */
public class frmVentas extends javax.swing.JFrame {
    ImageIcon Cromo=new ImageIcon();
    ImageIcon Escala=new ImageIcon();
    
    String imgautos;
    int auto;
    /**
     * Creates new form frmVentas
     */
    public frmVentas() {
        initComponents();
     Cromo=new ImageIcon(getClass().getResource("/Imagenes/frmTodo.jpg"));
     Escala=new ImageIcon(Cromo.getImage().getScaledInstance(lblFondo.getWidth(),lblFondo.getHeight(),Image.SCALE_DEFAULT));
     lblFondo.setIcon(Escala);
     
     Cromo=new ImageIcon(getClass().getResource("/Imagenes/lblAutos.jpg"));
     Escala=new ImageIcon(Cromo.getImage().getScaledInstance(lblAutos.getWidth(),lblAutos.getHeight(),Image.SCALE_DEFAULT));
     lblAutos.setIcon(Escala);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbllogo = new javax.swing.JLabel();
        panComprador = new javax.swing.JPanel();
        txtComprador = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        panModelos = new javax.swing.JPanel();
        cboModelos = new javax.swing.JComboBox<>();
        lblAutos = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        panSeguros = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        rdbSeguro1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblLema = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VENTAS");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo mini.jpg"))); // NOI18N
        lbllogo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, -1));

        panComprador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Comprador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(0, 102, 255))); // NOI18N
        panComprador.setOpaque(false);

        txtComprador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtComprador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        txtNumero.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Numero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        javax.swing.GroupLayout panCompradorLayout = new javax.swing.GroupLayout(panComprador);
        panComprador.setLayout(panCompradorLayout);
        panCompradorLayout.setHorizontalGroup(
            panCompradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCompradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panCompradorLayout.setVerticalGroup(
            panCompradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCompradorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panCompradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(panComprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        panModelos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panModelos.setOpaque(false);

        cboModelos.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cboModelos.setForeground(new java.awt.Color(0, 102, 255));
        cboModelos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MODELOS DE AUTOS:", "1-Nissan Versa", "2-Nissan NP300", "3-KIA Rio", "4-Chevrolet Aveo", "5-Nissan Sentra", "6-MG 5", "7-Nissan March ", "8-Mazda3", "9-Mazda2", "10-KIA Seltos", "11-Lamborghini", "12-Chevrolet Camaro SS", "13-Chevrolet Corvette", "14-Pagani Huayra", "15-Agera Koenigsegg" }));
        cboModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboModelosActionPerformed(evt);
            }
        });

        lblAutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAutos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panModelosLayout = new javax.swing.GroupLayout(panModelos);
        panModelos.setLayout(panModelosLayout);
        panModelosLayout.setHorizontalGroup(
            panModelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panModelosLayout.createSequentialGroup()
                .addGroup(panModelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panModelosLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panModelosLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(cboModelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panModelosLayout.setVerticalGroup(
            panModelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panModelosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(cboModelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(panModelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 340, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnCancelar.png"))); // NOI18N
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, -1, -1));

        panSeguros.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "MARCAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14), new java.awt.Color(0, 102, 255))); // NOI18N
        panSeguros.setOpaque(false);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup1.add(rdbSeguro1);
        rdbSeguro1.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        rdbSeguro1.setForeground(new java.awt.Color(255, 255, 255));
        rdbSeguro1.setText("KIA");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("FORD");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("NISSAN");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("CHEVROLET");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("TOYOTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbSeguro1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbSeguro1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addGap(24, 24, 24)
                .addComponent(jRadioButton4)
                .addGap(38, 38, 38)
                .addComponent(jRadioButton5)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panSegurosLayout = new javax.swing.GroupLayout(panSeguros);
        panSeguros.setLayout(panSegurosLayout);
        panSegurosLayout.setHorizontalGroup(
            panSegurosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSegurosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panSegurosLayout.setVerticalGroup(
            panSegurosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSegurosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panSeguros, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 360, 321));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnGarantia.png"))); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, 80, 80));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnPago_1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 600, 80, 80));

        lblLema.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 10)); // NOI18N
        lblLema.setForeground(new java.awt.Color(0, 153, 255));
        lblLema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLema.setText("\"Comprometidos con la seguridad,  dedicados a tu satisfaccion\"");
        lblLema.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblLema, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 320, 30));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 790, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboModelosActionPerformed
        
        switch (cboModelos.getSelectedIndex()) {
        
                case 0: imgautos="lblAutos.jpg";
                break;
                case 1: imgautos="versa.jpg";
                break;
                case 2: imgautos="NP300.jpg";
                break;
                case 3: imgautos="rio.jpg";
                break;
                case 4: imgautos="aveo.jpg";
                break;
                case 5: imgautos="sentra.jpg";
                break;
                case 6: imgautos="MG5.jpg";
                break;
                case 7: imgautos="March.jpg";
                break;
                case 8: imgautos="Mazda3.jpg";
                break;
                case 9: imgautos="Mazda2.jpg";
                break;
                case 10: imgautos="seltos.jpg";
                break;
                case 11: imgautos="lambo.jpg";
                break;
                case 12: imgautos="camaro.jpg";
                break;
                case 13: imgautos="corvette.jpg";
                break;
                case 14: imgautos="huayra.jpg";
                break;
                case 15: imgautos="koeni.jpg";
                break;
    }
        
     Cromo=new ImageIcon(getClass().getResource("/Imagenes/"+imgautos));
     Escala=new ImageIcon(Cromo.getImage().getScaledInstance(lblAutos.getWidth(),lblAutos.getHeight(),Image.SCALE_DEFAULT));
     lblAutos.setIcon(Escala);
    }//GEN-LAST:event_cboModelosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboModelos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JLabel lblAutos;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLema;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JPanel panComprador;
    private javax.swing.JPanel panModelos;
    private javax.swing.JPanel panSeguros;
    private javax.swing.JRadioButton rdbSeguro1;
    private javax.swing.JTextField txtComprador;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables

    private void Switch(int selectedIndex) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
